### ISSUE TITLE
Authenticating rtweet within shiny

### ISSUE THREAD

**Issue by ghost** [gadenbuie/tweet-conf-dash#2]
Hi Garrick, thanks for the app - it has been really useful for me as I learn shiny. 

I can run the app locally, which collects tweets from a list of users, updates an .rds containing all the tweets, and uses these throughout the app. I'm not sure if my issue is with shiny-rtweet authentication, or reading an RDS file in shiny.

When running on the shinyapps.io server, I get stopped at this error:

I have tried to use [this](https://github.com/mkearney/rtweet/issues/202#issuecomment-380692983) and [this](https://github.com/mkearney/rtweet/issues/202) advice, without luck. 

The log file I'm getting shows:

```
2019-09-01T14:17:51.765485+00:00 shinyapps[1133712]: Warning: Error in readRDS: error reading from connection
2019-09-01T14:17:51.769828+00:00 shinyapps[1133712]:   68: readRDS
2019-09-01T14:17:51.769831+00:00 shinyapps[1133712]:   67: is_tokenfile
2019-09-01T14:17:51.769832+00:00 shinyapps[1133712]:   66: twitter_pat
2019-09-01T14:17:51.769833+00:00 shinyapps[1133712]:   63: get_tokens
2019-09-01T14:17:51.769834+00:00 shinyapps[1133712]:   62: rate_limit
2019-09-01T14:17:51.769835+00:00 shinyapps[1133712]:   61: get_timeline_unlimited
2019-09-01T14:17:51.769836+00:00 shinyapps[1133712]:   60: get_user_tweets
2019-09-01T14:17:51.769838+00:00 shinyapps[1133712]:   59: server [/srv/connect/apps/candidates-2019-dash/server.R#9]
2019-09-01T14:17:51.770060+00:00 shinyapps[1133712]: Error in readRDS(x) : error reading from connection
```

You can see the function I use to collect the tweets [here:](https://github.com/pembletonc/candidates-2019-dash/blob/master/R/functions.R)

Not sure if this is the right place to add this question, not really an issue with your app - will migrate to SO if more suitable there!

**Comment by gadenbuie** [comment]
Hey Corey -- The issue is that your Twitter PAT didn't go along for the ride to shinyappsio. I just added a little code in [R/custom/00_settings.R](https://github.com/gadenbuie/tweet-conf-dash/blob/75c7759e9188b196b2a8dee6678fb7c3a59645b0/R/custom/00_settings.R#L89-L95) to catch this and give better guidance.

Basically, you'll need to locate the `.rds` file that rtweet created with your Twitter PAT and move a copy of that into your app folder before deploying up to shinyappsio. In the [linked commit](https://github.com/gadenbuie/tweet-conf-dash/commit/75c7759e9188b196b2a8dee6678fb7c3a59645b0) I set the app to find `.rtweet_token.rds` in the project directory, but you can also use a project-specific `.Renviron` as well. In either case, _don't commit the `.rds` file with your Twitter credentials to version control_!

Also FYI, this method definitely works in the technical sense, but I'm seeing memory issues when the update process runs. I've been running the app on Digital Ocean and can confirm that it's memory hungry. On shinyappsio though using too much memory might get the app killed.

**Comment by gadenbuie** [comment]
I missed a minor detail about how the tweet updating process is called, so the current best way is to use a project-specific `.Renviron`. Run `usethis::edit_r_environ("project")` and then add

```
TWITTER_PAT=".rtweet_token.rds"
```

to that file, and copy your rtweet token into your project folder.

**Comment by ghost** [comment]
Hey @gadenbuie thanks a lot, I have just been making the changes you suggested and am testing now, looks like it's up and running! https://data-break.shinyapps.io/candidates-2019-dash/

You're right about the memory, and I was a bit worried about that; I'm going to monitor it today and see how it goes, and also do some reading on building shiny apps to try to store things differently to get it running more efficiently. 

Thanks again, your help has been invaluable.

**Comment by gadenbuie** [comment]
Awesome! Good luck and hopefully things go smoothly from here!

In the long run and for general usability, I highly recommend separating the app from the tweet updating process. On the one hand because it's hard to recover the data directly from shinyappsio but also because it will likely be easier to manage. The [Shiny article on persistent data storage](http://shiny.rstudio.com/articles/persistent-data-storage.html) has some good advice for storage options. It depends on where/how you want to run the tweet updating scripts, but I'd think Amazon S3 would be at the top of my list to try out first.

**Comment by ghost** [comment]
Great, thanks for the article. Looks like it will be necessary, now that I see it running from shinyapps, it's making users wait for the script to update (e.g. collect more tweets) without showing anything while it's doing so. All part of the learning process! Cheers!
