### ISSUE TITLE
Self- contained app gets Twitter data but UI crashes

### ISSUE THREAD

**Issue by f0nzie** [gadenbuie/tweet-conf-dash#4]
Hi,
this is a great app. I wanted to to take a closer look. I like how you present the metrics.

I am using the self-contained version of your app. The master is giving me different sort of troubles I cannot follow. From the self- contained app I am getting this error:

![image](https://user-images.githubusercontent.com/29108853/74594431-099f2900-4ffc-11ea-9da1-0f1e52bd7cde.png)

I was able to get all the tweets gathered running first the `00-first-run.R` file.
![image](https://user-images.githubusercontent.com/29108853/74594477-9649e700-4ffc-11ea-8776-3bb29bead245.png)

The error seems to be coming from `ui.r`, here:

```
dashboardPage(
  # Dashboard Page Setup ----------------------------------------------------
  title = META$name,
  skin  = META$skin_color,
  theme = c(META$theme_css, "custom.css"),
  sidebar_mini = TRUE,
  dashboardHeader(
    title = HTML(glue::glue(
      '<span class="logo-mini">{META$logo_mini}</span>
      <span class="logo-lg">{META$logo_lg}</span>'
    ))
  ),
```

Any hints?

Thanks.

**Comment by gadenbuie** [comment]
Sorry about the confusion — I forked `shinydashboard` and added the `theme` argument because I wanted to cleanly load my own CSS.

The project dependencies are documented in `deps.yml`:

https://github.com/gadenbuie/tweet-conf-dash/blob/0317ac6e8f803c732380571037b5430acfea47cd/deps.yaml#L4-L8

Again sorry about the confusion — I fully intended to PR this back to shinydashboards but... life... 🤷‍♂ 

If you run into any other problems, feel free to open an issue as soon as you do and I'll answer. There's some self-inflicted wonkiness in this project and I'm happy to provide guidance around it.

**Comment by f0nzie** [comment]
Thanks.
on the **self-contained** app I did this:
I removed the `theme` object and getting error with `sidebar_mini = TRUE,`. Removed `sidebar_mini = TRUE,` 

![image](https://user-images.githubusercontent.com/29108853/74596387-2182a700-5014-11ea-9cad-5c39039cb04e.png)


and still getting another error: 
![image](https://user-images.githubusercontent.com/29108853/74596339-91446200-5013-11ea-872e-0da6ed6318a7.png).

Which is the branch I should be working with? The `master` or `self-contained`?
The master doesn't work either. I get different type of errors. There is no script `01-first-run.R` in the master.

Thanks.

**Comment by gadenbuie** [comment]
There are a few other things I changed in my fork of `shinydashboard`, not just the `theme` argument. De-tangling my forked version from the app would take a bit of work, but it's doable. But I would use `self-contained` branch.

**Comment by PatronMaster** [comment]
Hi, 

Thanks for answer in my post. I just have time now to fix.
I am now with same error:
` Error in dashboardPage: unused arguments (theme = c(META$theme_css, "custom.css"), sidebar_mini = TRUE)`

I read this post several times I do not understand what I need to do in order to fix.
I download again the last release but still have the same error.

**Comment by gadenbuie** [comment]
If you install my fork of shinydashboard, this app should work. Use this code:

```r
devtools::install_github("gadenbuie/shinydashboard@2dfe619d92193de2b0b1d74be48798f994ea882b")
```

I would recommend using docker or [renv](https://github.com/rstudio/renv) or a similar process to ensure that you're only using my shinydashboard fork for this app rather than installing it globally on your computer.

**Comment by PatronMaster** [comment]
It works, I used renv instead of container. It is amazing package this give to us lot's of possibilities. Thanks
